// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file example/v1/example/example_service.proto (package example.example.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginRequest, LoginResponse } from "./example_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service example.example.v1.ExampleService
 */
export const ExampleService = {
  typeName: "example.example.v1.ExampleService",
  methods: {
    /**
     * @generated from rpc example.example.v1.ExampleService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

